version:
    '3.1'
services:
    app:
        container_name: kayayo
        restart:
            always
        ports:
            - 1900:1900
        build: .
        
        networks:
            - app-network
         
            mydb:
                image: postgres
                volumes:
                - db-data:/var/lib/postgresql/data
                ports:
                - 5432:5432
                networks: 
                - app-network
                environment: 
                - POSTGRES_USER=quaci
                - POSTGRES_PASSWORD=kayayo
                 
                volumes:
                db-data:
                driver: local
       
    
networks:
    app-network:
      driver: bridge


    



